### ISSUE TITLE
Advanced GH Action: upload apt, zyp, yum packages into S3 bucket

### ISSUE THREAD

**Issue by brushknight** [newrelic/infrastructure-publish-action#22]
Goal: publish packages for apt, yam, rpm, zyp packages managers

Requirement: newrelic/nri-redis#99  (in review)

Steps:
- [x] Add pre-prod (/test) flag & schemas
- [ ] Locking mechanism (file based)
- [x] Review metadata signing
- [x] Publish into YUM repo with metadata regeneration
- [x] Publish into ZYPP repo with metadata regeneration
- [x] Publish into APT repo with incrementing metadata
- [ ] Publishing from GH actions

Tasks:
- [x] APT: mirror current repo only if needed (Paolo)
- [x] APT: infra-agent service managers (Juan)
- [x] YUM, ZYPP, APT: update default schemas - infra-agent (Juan)
- [x] YUM, ZYPP, APT: update default schemas - ohi, nrjmx (Paolo)
- [x] APT: test install, upgrade
- [ ] APT: test in GH to check limitations (7GB download) Validation will be done in [Integrate publish action into agent pipelines (first: msi, tar.gz, zip)](https://github.com/newrelic/infrastructure-agent/issues/290)
- [x] ZYPP: test install, upgrade
- [x] YUM: test install, upgrade
- [ ] Locking mechanism
- [x] Fix snyk (Paolo)
- [ ] Update documentation

Notes:
- ~For each repo should be different tag, ex: `:apt` for apt repo, `:zyp` or `:zypper` for zypper repo.~
- ~Some PoC can be find [here](https://github.com/newrelic/nri-redis/pull/94/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R1).~
